### ISSUE TITLE
Your mod is good

### ISSUE THREAD

**Issue by KsenofAlike** [ThomasThings/erekir-scaled#1]
I really like your pixel art and i hope that this mod will expand. Good luck! Also, can you change blocks's name to normal?

**Comment by ThomasThings** [comment]
Thanks, I really appreciate that. 

Although, I'm not sure what you mean by change the block's names back to normal.

**Comment by KsenofAlike** [comment]
All blocks are named like "es-berillium-wall-huge" i meant to give them normal name. Huge berillium wall

**Comment by ThomasThings** [comment]
Well, The game's engine can't load blocks with spaces in their names. That's just the naming convention for everything in mindustry. The "es" at the beginning is how I organize things as well, to separate the categories of images on my laptop.

**Comment by ThomasThings** [comment]
If you mean it shows up like that in game, That's because I have done almost no work on the mod. It's mega pre-alpha.
